version: 1
build:
  main: ./cmd/arkeod
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
genesis:
  chain_id: "arkeo-local"
  app_state:
    staking:
      params:
        bond_denom: "ukeo"
accounts:
- name: reserve
  coins:
  - 2000000000000000ukeo
  address: rko1dheycdevq39qlkxs2a6wuuzyn4aqxhvee2kjas
- name: alice
  coins:
  - 200000000000000ukeo
- name: bob
  coins:
  - 1000000000000ukeo
faucet:
  name: bob
  coins:
  - 5keo
  host: 0.0.0.0:4500
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000ukeo
