before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=1

builds:
  - id: arkeod-darwin-amd64
    binary: arkeod
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    main: ./cmd/arkeod
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{ .CommitDate }}
      - -X github.com/cosmos/cosmos-sdk/version.Name=Arkeo
      - -X github.com/cosmos/cosmos-sdk/version.AppName=arkeo
      - -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{ .Env.BUILD_TAG }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.Version=v{{ .Version }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.GitCommit={{ .Commit }}
      - -w -s
      - -linkmode=external
    tags:
      - '{{ .Env.BUILD_TAG }}'

  - id: arkeod-darwin-arm64
    binary: arkeod
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    main: ./cmd/arkeod
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{ .CommitDate }}
      - -X github.com/cosmos/cosmos-sdk/version.Name=Arkeo
      - -X github.com/cosmos/cosmos-sdk/version.AppName=arkeo
      - -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{ .Env.BUILD_TAG }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.Version=v{{ .Version }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.GitCommit={{ .Commit }}
      - -w -s
      - -linkmode=external
    tags:
      - '{{ .Env.BUILD_TAG }}'

  - id: arkeod-linux-arm64
    binary: arkeod
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    main: ./cmd/arkeod
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.commit={{.Commit}}
      - -X main.date={{ .CommitDate }}
      - -X github.com/cosmos/cosmos-sdk/version.Name=Arkeo
      - -X github.com/cosmos/cosmos-sdk/version.AppName=arkeo
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{ .Env.BUILD_TAG }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.Version=v{{ .Version }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.GitCommit={{ .Commit }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs --static -lm'
    tags:
      - '{{ .Env.BUILD_TAG }}'

universal_binaries:
  - id: arkeod-darwin-universal
    ids:
      - arkeod-darwin-amd64
      - arkeod-darwin-arm64
    replace: false
    name_template: >-
      {{ .ProjectName }}d_{{ .Version }}_darwin_universal
      {{- if eq .Env.BUILD_TAG "testnet" }}_testnet{{ end }}

archives:
  - id: archive-versioned
    builds:
      - arkeod-linux-arm64
      - arkeod-darwin-amd64
      - arkeod-darwin-arm64
      - arkeod-darwin-universal
    name_template: >-
      {{ .ProjectName }}d_{{ .Version }}_{{ .Os }}_{{ .Arch }}
      {{- if eq .Env.BUILD_TAG "testnet" }}_testnet{{ end }}
    wrap_in_directory: false
    format: zip
    files:
      - none*

  - id: archive-binary
    builds:
      - arkeod-linux-arm64
      - arkeod-darwin-amd64
      - arkeod-darwin-arm64
      - arkeod-darwin-universal
    name_template: >-
      {{ .ProjectName }}d_{{ .Os }}_{{ .Arch }}
      {{- if eq .Env.BUILD_TAG "testnet" }}_testnet{{ end }}
    wrap_in_directory: false
    format: binary
    files:
      - none*

checksum:
  name_template: >-
    {{ .ProjectName }}d_{{ .Version }}
    {{- if eq .Env.BUILD_TAG "testnet" }}_testnet{{ end }}
    {{- "_cross_checksums.txt" }}

dockers:
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: docker/Dockerfile
    image_templates:
      # Latest tag
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}:latest-arm64'
      # Version tag
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}:{{ .Version }}-arm64'
      # Testnet tags if applicable
      - '{{ if eq .Env.BUILD_TAG "testnet" }}ghcr.io/arkeonetwork/{{ .ProjectName }}:testnet-latest-arm64{{ end }}'
      - '{{ if eq .Env.BUILD_TAG "testnet" }}ghcr.io/arkeonetwork/{{ .ProjectName }}:testnet-{{ .Version }}-arm64{{ end }}'
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=arkeod"
      - "--label=org.opencontainers.image.description=Arkeo Daemon"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://arkeo.network/"
      - "--label=org.opencontainers.image.source=https://github.com/arkeonetwork/arkeo"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: docker/Dockerfile.dev
    image_templates:
      # Latest dev tag
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:latest-arm64'
      # Version dev tag
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:{{ .Version }}-arm64'
      # Testnet dev tags if applicable
      - '{{ if eq .Env.BUILD_TAG "testnet" }}ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:testnet-latest-arm64{{ end }}'
      - '{{ if eq .Env.BUILD_TAG "testnet" }}ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:testnet-{{ .Version }}-arm64{{ end }}'
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=arkeod-dev"
      - "--label=org.opencontainers.image.description=Arkeo Daemon Development Build"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://arkeo.network/"
      - "--label=org.opencontainers.image.source=https://github.com/arkeonetwork/arkeo"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

docker_manifests:
  # Production manifests
  - name_template: 'ghcr.io/arkeonetwork/{{ .ProjectName }}:latest{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'
    image_templates:
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}:latest-amd64{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}:latest-arm64{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'

  - name_template: 'ghcr.io/arkeonetwork/{{ .ProjectName }}:{{ .Version }}{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'
    image_templates:
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}:{{ .Version }}-amd64{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}:{{ .Version }}-arm64{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'

  # Development manifests
  - name_template: 'ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:latest{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'
    image_templates:
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:latest-amd64{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:latest-arm64{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'

  - name_template: 'ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:{{ .Version }}{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'
    image_templates:
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:{{ .Version }}-amd64{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}-dev:{{ .Version }}-arm64{{ if eq .Env.BUILD_TAG "testnet" }}-testnet{{ end }}'

release:
  skip_upload: '{{ if eq .Env.RELEASE "true" }}false{{else}}true{{end}}'