before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=1

builds:
  - id: api-linux-amd64
    binary: api
    main: ./cmd/directory/api
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X main.commit={{.Commit}}
      - -X main.date={{ .CommitDate }}
      - -X github.com/cosmos/cosmos-sdk/version.Name=Arkeo
      - -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.AppName=arkeo
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{ .Env.BUILD_TAG }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.Version=v{{ .Version }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.GitCommit={{ .Commit }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs --static -lm'
    tags:
      - '{{ .Env.BUILD_TAG }}'
  
  - id: indexer-linux-amd64
    binary: indexer
    main: ./cmd/directory/indexer
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X main.commit={{.Commit}}
      - -X main.date={{ .CommitDate }}
      - -X github.com/cosmos/cosmos-sdk/version.Name=Arkeo
      - -X github.com/cosmos/cosmos-sdk/version.Version=v{{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.AppName=arkeo
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags={{ .Env.BUILD_TAG }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.Version=v{{ .Version }}
      - -X github.com/arkeonetwork/arkeo/x/arkeo/configs.GitCommit={{ .Commit }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs --static -lm'
    tags:
      - '{{ .Env.BUILD_TAG }}'

archives:
  - id: archive-versioned
    builds:
      - api-linux-amd64
      - indexer-linux-amd64
    name_template: >-
      directory_{{ .Version }}_{{ .Os }}_{{ .Arch }}
      {{- if eq .Env.BUILD_TAG "testnet" }}_testnet{{ end }}
    wrap_in_directory: false
    format: zip
    files:
      - none*

  - id: archive-binary
    builds:
      - api-linux-amd64
      - indexer-linux-amd64
    name_template: >-
      directory_{{ .Os }}_{{ .Arch }}
      {{- if eq .Env.BUILD_TAG "testnet" }}_testnet{{ end }}
    wrap_in_directory: false
    format: binary
    files:
      - none*

checksum:
  name_template: >-
    directory_{{ .Version }}
    {{- if eq .Env.BUILD_TAG "testnet" }}_testnet{{ end }}
    {{- "_checksums.txt" }}

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.api
    image_templates:
      # Latest API tag
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}/api:latest-amd64'
      # Version API tag
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}/api:{{ .Version }}-amd64'
      # Testnet tags if applicable
      - '{{ if eq .Env.BUILD_TAG "testnet" }}ghcr.io/arkeonetwork/{{ .ProjectName }}/api:testnet-latest-amd64{{ end }}'
      - '{{ if eq .Env.BUILD_TAG "testnet" }}ghcr.io/arkeonetwork/{{ .ProjectName }}/api:testnet-{{ .Version }}-amd64{{ end }}'
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=directory-api"
      - "--label=org.opencontainers.image.description=Arkeo Directory API Service"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://arkeo.network/"
      - "--label=org.opencontainers.image.source=https://github.com/arkeonetwork/arkeo"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.indexer
    image_templates:
      # Latest indexer tag
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}/indexer:latest-amd64'
      # Version indexer tag
      - 'ghcr.io/arkeonetwork/{{ .ProjectName }}/indexer:{{ .Version }}-amd64'
      # Testnet tags if applicable
      - '{{ if eq .Env.BUILD_TAG "testnet" }}ghcr.io/arkeonetwork/{{ .ProjectName }}/indexer:testnet-latest-amd64{{ end }}'
      - '{{ if eq .Env.BUILD_TAG "testnet" }}ghcr.io/arkeonetwork/{{ .ProjectName }}/indexer:testnet-{{ .Version }}-amd64{{ end }}'
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=directory-indexer"
      - "--label=org.opencontainers.image.description=Arkeo Directory Indexer Service"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://arkeo.network/"
      - "--label=org.opencontainers.image.source=https://github.com/arkeonetwork/arkeo"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

release:
  skip_upload: '{{ if eq .Env.RELEASE "true" }}false{{else}}true{{end}}'