name: Mercury CI
run-name: ${{ github.actor }} is testing a code change 🚀
on: [push]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
          # cache: true
      - name: Version
        uses: ignite-hq/cli/actions/cli@v0.24.0 # building protobuf files pb.go
        with:
          args: version
      - name: Compile Protobuf
        uses: ignite-hq/cli/actions/cli@v0.24.0 # building protobuf files pb.go
        with:
          args: chain build --yes --proto-all-modules
      - name: Lint code
        run: |
          make lint-ci
      - name: Unit Tests
        run: |
          sudo rm -rf vue
          make test
