name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: ${{ matrix.release }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: ["release", "release-cross","release-testnet","release-testnet-cross","sentinel-release-cross","sentinel-testnet-cross","sentinel-release","sentinel-testnet-release","directory-release-cross","directory-testnet-cross","directory-release","directory-testnet"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: ${{ matrix.release }}
        env:
          RELEASE: true
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: make ${{ matrix.release }}